# Generated by Django 3.0.8 on 2020-07-29 04:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200728_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='output',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
